name: mlops-example-tensorflow-regression

on: [push]  # You can change this to `pull_request` for better commenting in PRs

permissions:
  contents: write        # Required for commit comments
  pull-requests: write   # Required for PR comments

jobs:
  run:
    runs-on: ubuntu-latest
    # Optionally use a container with preinstalled DVC + CML
    # container: ghcr.io/iterative/cml:0-dvc2-base1

    steps:
      - uses: actions/checkout@v3

      # Optionally set up Python explicitly if required
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'

      - uses: iterative/setup-cml@v1

      - name: Train model
        env:
          TF_CPP_MIN_LOG_LEVEL: "2"  # Suppress TensorFlow CUDA warnings
        run: |
          pip install -r requirements.txt
          python model.py

      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat results.txt >> report.md
          cml comment create --target=commit report.md
